# fly.toml app configuration file generated for resourc on 2023-11-06T08:53:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resourc"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
